import json,html,shutil,zipfile
from pathlib import Path
from PIL import Image,ImageDraw
P=Path(__file__).resolve().parents[1]; OLD=P.parent/'ui-review-2026-09-09'
x=json.loads((OLD/'report/review.json').read_text()); shots=json.loads((P/'screenshots.json').read_text()); oldshots=json.loads((OLD/'screenshots.json').read_text())
x['date']='10. September 2026'
x['title']='Shipyard · Produkt- und UI-Review · erneute Live-Prüfung'
x['summary']='Shipyard bietet einen sinnvollen, umfangreichen Funktionskern für den Infrastruktur-Betrieb. Die dunkle Oberfläche, Navigation, Tabellen und Statusfarben bilden eine professionelle Basis. Meine Enterprise-Einschätzung bleibt bei etwa 6,5 von 10: Die größten Lücken liegen in verlässlichen Informationen, sicheren Standardwerten und geführten Arbeitsabläufen. Ein neues Theme hätte deutlich weniger Nutzen als konsistente Zeiten, eindeutige Ressourcenbegriffe und verständliche Handlungsschritte.'
x['scope']=f"Erneute Live-Prüfung der angemeldeten Admin-Oberfläche unter https://shipyard/ am 10. September 2026. {len(shots)} neue Desktop-Screenshots erfassen Hauptseiten, die wesentlichen Tabs, repräsentative Host-/VM-/CT-Details und zentrale Dialoge. Die 35 Featurebewertungen bauen auf dem vorhandenen Review vom 9. September auf und wurden anhand der aktuellen Aufnahmen abgeglichen. 74 ältere Aufnahmen bleiben separat als datierte Ergänzung enthalten; sie sind keine neuen Screenshots. Neue Aufnahmen zeigen den sichtbaren Bildschirmausschnitt (1414 × 873), ältere Aufnahmen enthalten ergänzende Ganzseitenansichten. Nicht jede einzelne Ressourceninstanz und nicht jeder mögliche Dialogzustand wurde wiederholt."
x['limits']='Keine Infrastrukturaktionen, Formularspeicherungen, Neustarts, Updates, Löschungen, Testnachrichten oder Deployments ausgeführt. Der Dateibrowser wurde lesend geöffnet; das SSH-Terminal wurde bei dieser erneuten Prüfung nicht verbunden. Terminal-, Editor-, Rollen- und weitere Formularvertiefungen stammen teilweise aus dem separat gekennzeichneten Vorreview. Login/Onboarding, MFA-Aktivierung, Rollenisolierung, mobile Ansichten und vollständige Barrierefreiheit wurden nicht geprüft. Aktive Pluginseiten, Agentbetrieb und deklarative VM-Ausführungszustände sind mangels aktivierter bzw. vorhandener Instanzen nicht live bewertbar. Fehlende Funktionen bedeuten hier: in den geprüften Oberflächen nicht sichtbar oder auffindbar. Scores sind qualitative Einschätzungen und keine technische Sicherheitszertifizierung.'
x['code_note']='Die lokale Arbeitskopie enthält bereits umfangreiche Änderungen und entspricht erkennbar nicht vollständig der Live-Oberfläche. Beispiel: users-roles.tsx Zeile 296 startet die Rollenauswahl leer; Zeile 301 verlangt eine explizite Rolle. Live ist weiterhin User vorausgewählt. operations.tsx enthält bereits strukturierte resource_scope-Felder, während die Live-Wartungsmaske Freitext zeigt. Die Befunde bewerten daher die bereitgestellte App; lokal vorhandene Änderungen sind kein Nachweis einer produktiven Behebung. Dies ist ein UI-/Produktreview mit gezieltem Quellenabgleich, kein vollständiger Code- oder Security-Audit. In diesem Durchgang wurden keine Quellcodedateien geändert.'
fm=[[1],[2],[3,4],[5],[6],[7],[8,9],[10],[11],[12],[13],[14],[15,16,18],[19],[20],[21],[22,23],[24],[54],[38,39,40,45,46],[41,50,51,63,64,65,66],[42,47],[43,48],[44,49,52,53,67],[35,36,37],[34],[55,56],[25,57,58],[26],[27,28,29,58],[30],[31],[32],[33],[59,60,61,62]]
for i,f in enumerate(x['features']):
 f['baselineShots']=f['shots'];f['shots']=fm[i]
 f['evidence']='Neue Live-Aufnahmen; ergänzende Detailzustände im Vorreview vom 9. September.'
x['features'][6]['info']='IPAM- und Proxmox-Links sind nützlich. Aktuell zeigt der Host RAM-Warnung und Updates: Healthy; Image-Updates waren bei dieser Aufnahme nicht offen. Der ältere Konflikt zwischen Healthy und Image-Updates ist heute somit nicht erneut reproduziert. API Latency bleibt ohne klare fachliche Bedeutung; Zeitpunkt und Trends fehlen.'
x['features'][6]['ui']='Gute Abschnitte und Ressourcenbalken. Die aktuelle RAM-Warnung und der getrennte Updatezustand sind fachlich vereinbar; ein allgemeiner Gesamtstatus sollte den Warnzustand eindeutig zusammenfassen.'
x['features'][31]['use']='Fehlerbenachrichtigungen außerhalb der Konsole sind für den Betrieb wesentlich. Die angebotenen Ereignistypen müssen zum tatsächlich aktiven Funktionsumfang passen.'
x['features'][32]['ui']='Lange Seite mit heterogenen Aufgaben von Binary-Installation über Polling bis Agentkonfiguration.'
x['features'][7]['info']='Image- und Laufzustand helfen. CPU und Memory zeigen bei allen sichtbaren Containern Striche; selbst gebaute Images melden Cannot check ohne erklärten nächsten Schritt. Der Spaltenname Check for Updates benennt eine Aktion statt den angezeigten Zustand.'
x['features'][20]['info']='Managementzustand und Ressourcen sind vorhanden. Gestoppte VMs heißen im Baum Unknown; IP und Disk fehlen teilweise. LXC-Details zeigen dieselben VM-Felder wie BIOS, Boot order, Cloud-Init und QEMU agent, obwohl diese Darstellung zum Ressourcentyp nicht passt.'
x['features'][20]['improve']+=' LXC und QEMU getrennt modellieren: nur anwendbare Felder anzeigen und fehlende Daten nicht als deaktivierte VM-Funktion darstellen.'
x['features'][26]['ui']='Der Dialog Platform connections schneidet bei 1414 × 873 rechts Text, Connect-Schaltfläche und Aktionsspalte ab. Danach öffnet sich ein zweiter Dialog. Sprachmischung und dieser Überlauf schwächen den Enterprise-Eindruck deutlich.'
x['features'][26]['scores'][3]=2
x['features'][26]['improve']='Zuerst den horizontalen Überlauf beheben: Dialogbreite begrenzen, Kinder schrumpfbar machen und Tabelle gezielt scrollbar halten. Danach Verbindungen in eine eigene Seite oder einen flachen Dialog führen; Rechtecheck, CA-Zertifikatsweg und Service-Account-Beispiel ergänzen.'
x['features'][34]['info']='Command Palette und Umgebungskontext sind gut zugänglich. Activity Center zeigt jetzt 2 recent mit generischem Server action; der Zeitraum bleibt unklar. Die Umgebung meldet 1 deployment trotz leerer Managed-VM-Liste. Help enthält nur GitHub und Issues; im Linux-Kontext steht weiterhin ⌘K.'
x['features'][11]['evidence']='Dateibrowser aktuell aufgenommen; Terminal selbst nur im Vorreview vom 9. September, diesmal nicht verbunden.'
x['features'][13]['evidence']='Inventar aktuell; YAML-Editor und seine Bedienung ergänzend aus dem Vorreview vom 9. September.'
x['features'][15]['evidence']='Variablenübersicht aktuell; Eingabedialog ergänzend aus dem Vorreview vom 9. September.'
x['features'][29]['evidence']='Benutzerformular, Rollenübersicht und Konto aktuell; ausführlicher Rollen-Editor ergänzend aus dem Vorreview vom 9. September.'
findshots=[[2,8,12,20,22,44,55],[1,43,48],[15,38,50,54,60],[36,37],[28,29],[2,5,12,59],[18,23],[10,41,50,51],[4,48,50,67],[22,39,46,56]]
for f,s in zip(x['findings'],findshots):f['baselineShots']=f['shots'];f['shots']=s
x['findings'][0]['observation']='Derselbe Compose-Lauf vom 9. September erscheint in Operations um 19:35 und in der Hosthistorie um 21:35. Playbook Runs zeigt den geplanten Start 01:00, die Hosthistorie 03:00. IPAM-Sync erscheint in Plattform-Tasks am 9. September um 23:18 und unter Platform connections am 10. September um 01:18. Damit betrifft die Abweichung auch das Datum.'
x['findings'][1]['observation']='Das Dashboard nennt für pve001 3 OS-Updates, die Proxmox-Ansicht 5. Beide Quellen können unterschiedliche Kataloge haben; der Zusammenhang und Datenstand werden aber nicht ausreichend erklärt. Der im Vorreview beobachtete Konflikt Healthy trotz Image-Updates war heute mangels offener Image-Updates nicht erneut reproduzierbar.'
x['findings'][1]['acceptance']='Quellen und Prüfzeitpunkte sind sichtbar. Unterschiedliche Updatezahlen werden erklärt; Gesamtstatus wird bei bekannten Image-, OS- und Custom-Updates konsistent berechnet und mit passenden Testfällen geprüft.'
x['findings'][2]['observation']='Managed VMs ist leer, die Plattform nennt 12 managed in Shipyard, die Umgebung 1 deployment. Infrastructure meldet 2 external hosts, der Baum 1 Standalone host. Dieselbe Ressource heißt als VM hr01-med-services02 und als Host hr01-media-hms. Die Details verlinken beide Objekte, aber Begriffe, Zähler und Baumklickziele bleiben uneinheitlich.'
x['findings'][5]['observation']='Operations zeigt compose_up_hms, compose_pull_hms und lange vm-UUIDs; die ausgewählte Detailkarte wiederholt Tabellenfelder und führt zur Hostseite statt direkt zum Lauf. Activity Center nennt zwei unterschiedliche Vorgänge lediglich Server action. Die Hosthistorie mischt lesbare Titel und technische Codes.'
x['findings'][7]['observation']='Container-CPU und Memory zeigen Striche; selbst gebaute Images Cannot check. VM-Disk und IP heißen teils Not reported bei konfiguriertem QEMU agent Enabled. Gestoppte VMs werden im Baum Unknown genannt. Grund, Erhebungszeit und nächste Maßnahme fehlen.'
x['findings'].extend([
 {'id':'P2-06','title':'Abgeschnittenen Verbindungsdialog reparieren','shots':[55,56],'observation':'Bei Desktopgröße 1414 × 873 überschreitet der Inhalt von Platform connections die Dialogbreite. Einleitung und Connect-Schaltfläche sind rechts abgeschnitten; die Aktionsspalte liegt außerhalb des sichtbaren Bereichs.','impact':'Zentrale Verwaltungselemente sind schlecht auffindbar bzw. sichtbar unvollständig. Der Überlauf beeinträchtigt die Bedienbarkeit.','change':'Schrumpfbare Layout-Kinder (min-width:0), passende Dialogbreite und kontrolliertes Tabellen-Scrolling verwenden; Einleitung umbrechen. Verschachtelte Dialoge durch einen flachen Ablauf ersetzen.','acceptance':'Bei 1280, 1440 und 1920 Pixeln sowie 200% Zoom sind Dialogtitel, primäre Aktion und Schließen vollständig erreichbar; horizontales Scrolling ist auf die Tabelle beschränkt.'},
 {'id':'P2-07','title':'LXC-Informationen an den Ressourcentyp anpassen','shots':[63,64],'observation':'Die LXC-Detailseite verwendet Hardware & virtual machine und zeigt QEMU agent: Disabled, BIOS / machine: Proxmox default, Boot order und Cloud-Init user.','impact':'Nicht anwendbare VM-Informationen sehen wie fehlende oder fehlerhafte Containerkonfiguration aus.','change':'Eigene Feldgruppen für LXC und QEMU: LXC-OS, Rootfs, Mounts, Netz, Privilegierung und passende Limits zeigen; VM-spezifische Felder ausblenden.','acceptance':'Eine LXC-Seite enthält keine QEMU-/BIOS-Defaults; unbekannt und nicht anwendbar sind unterscheidbar.'}
])
x['roadmap']=[
 {'phase':'P1 · Vertrauen und Standardwerte','items':['Zeitformat und Zeitzone über alle Ansichten vereinheitlichen.','Host-, VM- und Deployment-Zähler sowie Updatequellen eindeutig definieren.','Reservierungsdefault auf Reserved setzen und nächste freie IP vorfüllen.','Neue Benutzer erst nach bewusster Rollenwahl anlegen; effektive Rechte zeigen.']},
 {'phase':'P2 · Tägliche Bedienung','items':['Dialogüberlauf beheben; VM-, Zeitplan- und Rollenformulare in prüfbare Schritte gliedern.','Operations direkt mit konkreten Runs und Logs verknüpfen.','Unbekannte Metriken erklären, gestoppte Ressourcen korrekt kennzeichnen und LXC-Felder bereinigen.','Sprache, Statusvokabular, Tabellenfilter und Aktionshierarchie vereinheitlichen.']},
 {'phase':'Enterprise-Ausbau · nach Zielkunden priorisieren','items':['Wartungsfenster mit echten Ressourcen, Zuständigkeit, Konflikten und Change-Referenz verbinden.','Einladungen, MFA-Policy, SSO und Sessionverwaltung anhand konkreter Kundenanforderungen planen.','Zustellhistorie, Routing und Wartungsunterdrückung für Benachrichtigungen; sichere Wiederherstellung und nachvollziehbare Releases ausbauen.','Vor Produktionsfreigabe: lokale Änderungen gegen den Live-Stand abgleichen sowie Rechte, Fehlerfälle, mobile Ansichten und Tastaturbedienung separat testen.']}
]
(P/'report/review.json').write_text(json.dumps(x,ensure_ascii=False,indent=2))
# Keep previous evidence explicitly dated; only copy screenshot evidence, never implementation fixtures.
(P/'baseline-2026-09-09').mkdir(exist_ok=True)
for i,s in enumerate(oldshots,1):
 src=OLD/s.get('fullpage','')
 if not src.is_file():src=Path(s['file'])
 shutil.copy2(src,P/'baseline-2026-09-09'/f'{i:02d}.png')
E=html.escape
cur={i:f"screenshots/{s['file']}" for i,s in enumerate(shots,1)}
def refs(ids,baseline=False):
 return ' · '.join(f'<a href="{("baseline-2026-09-09/%02d.png"%i) if baseline else cur[i]}" target="_blank">{"B" if baseline else "N"}{i:02d}</a>' for i in ids)
head='''<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shipyard · UI-Review</title><style>
:root{color-scheme:light;font-family:Inter,system-ui,sans-serif;color:#192b3c;background:#f3f5f8}*{box-sizing:border-box}body{margin:0}header{background:#142638;color:#fff;padding:44px max(24px,calc((100vw - 1200px)/2));}header p{max-width:960px;color:#d5e2ee;line-height:1.6}main{max-width:1250px;margin:auto;padding:24px}h1{font-size:36px;margin:6px 0 16px}h2{font-size:26px;margin:36px 0 16px}h3{margin:0 0 12px;font-size:20px}p{line-height:1.6}a{color:#126289}header a{color:#adddfb}nav{display:flex;gap:18px;flex-wrap:wrap;margin-top:24px}.label{font-size:12px;letter-spacing:.1em;text-transform:uppercase}.card{background:#fff;padding:24px;border:1px solid #dce2e9;border-radius:10px;margin:16px 0}.muted{color:#526779;font-size:14px}.scores{display:flex;gap:12px;flex-wrap:wrap}.score{background:#eaf1f7;padding:10px 12px;border-radius:5px}.score strong{font-size:20px}.priority{color:#9a441b}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}figure{margin:0;background:white;border:1px solid #dce2e9;border-radius:8px;overflow:hidden}figure img{display:block;width:100%;height:auto}figcaption{padding:12px;font-size:13px}.tablewrap{overflow:auto}table{border-collapse:collapse;width:100%;background:white}td,th{padding:12px;border-bottom:1px solid #dce2e9;text-align:left}th{background:#e5edf3}details{margin-top:14px}summary{cursor:pointer;font-weight:600}input{font:inherit;width:100%;padding:13px;border:1px solid #9fafbd;border-radius:6px}dt{font-weight:700;margin-top:14px}dd{margin:5px 0 12px;line-height:1.6}.hidden{display:none}.notice{border-left:4px solid #cd8527;padding:16px 20px;background:#fff6e5}li{line-height:1.6;margin:8px 0}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}main{padding:16px}h1{font-size:28px}}@media(max-width:520px){.grid{grid-template-columns:1fr}}@media print{header{background:white;color:#172b3d;padding:0}header p{color:#333}nav,input,.gallery{display:none}.card{break-inside:avoid}body{background:white}}
</style><header><div class="label">Produkt & Bedienbarkeit · 10. September 2026</div><h1>Shipyard: starkes Werkzeug,<br>noch keine durchgängig reife Enterprise-Konsole.</h1>'''
parts=[head,f'<p>{E(x["summary"])}</p><nav><a href="#findings">12 priorisierte Befunde</a><a href="#features">35 Featurebewertungen</a><a href="#gallery">{len(shots)} neue Screenshots</a><a href="#scope">Prüfumfang</a><a href="bericht.md">Textbericht</a></nav></header><main>',f'<section id="scope"><h2>Prüfumfang und Nachweise</h2><p>{E(x["scope"])}</p><p class="muted">{E(x["limits"])}</p><div class="notice">{E(x["code_note"])}</div><p><b>N01–N{len(shots):02d}</b> = neue Aufnahmen vom 10. September. <b>B01–B74</b> = ergänzende Aufnahmen vom 9. September. Links öffnen Originalbilder.</p></section>', '<section id="findings"><h2>Was zuerst verbessert werden sollte</h2>']
md=[f'# {x["title"]}',x['date'],x['summary'],'## Prüfumfang',x['scope'],x['limits'],'## Verhältnis zum Code',x['code_note'],'## Priorisierte Befunde']
for f in x['findings']:
 parts.append(f'<article class="card"><div class="label priority">{E(f["id"])}</div><h3>{E(f["title"])}</h3><dl>'+''.join(f'<dt>{label}</dt><dd>{E(f[key])}</dd>' for key,label in [('observation','Beobachtung'),('impact','Auswirkung'),('change','Verbesserung'),('acceptance','Abnahmekriterium')])+f'</dl><p>Aktuelle Belege: {refs(f["shots"])}</p></article>')
 md.extend([f'### {f["id"]} · {f["title"]}',f'**Beobachtung:** {f["observation"]}',f'**Auswirkung:** {f["impact"]}',f'**Verbesserung:** {f["change"]}',f'**Abnahme:** {f["acceptance"]}','Belege: '+', '.join(f'[N{i:02d}]({cur[i]})' for i in f['shots'])])
parts+=['</section><section id="features"><h2>Alle 35 Featurebereiche</h2>',f'<p>{E(x["scale"])}</p><label for="filter">Features durchsuchen</label><input id="filter" placeholder="z. B. IPAM, Rollen, Eingaben …"><p id="count" class="muted">35 Bereiche</p><div class="tablewrap"><table><thead><tr><th>Feature</th>'+''.join(f'<th>{E(c)}</th>' for c in x['criteria'])+'</tr></thead><tbody>']
for i,f in enumerate(x['features']):parts.append(f'<tr data-feature="feature-{i}"><td><a href="#feature-{i}">{E(f["name"])}</a></td>'+''.join(f'<td>{v if v is not None else "—"}</td>' for v in f['scores'])+'</tr>')
parts.append('</tbody></table></div>');md+=['## Bewertung aller Features',x['scale']]
for i,f in enumerate(x['features']):
 parts.append(f'<article class="card feature" id="feature-{i}"><h3>{E(f["name"])}</h3><div class="scores">'+''.join(f'<div class="score">{E(c)} <strong>{v if v is not None else "—"}</strong>/5</div>' for c,v in zip(x['criteria'],f['scores']))+'</div><dl>'+''.join(f'<dt>{label}</dt><dd>{E(f[key])}</dd>' for key,label in [('use','Ist die Funktion sinnvoll?'),('info','Sind die Informationen nützlich?'),('inputs','Passen die Eingaben?'),('ui','Gestaltung und Enterprise-Wirkung'),('improve','Konkrete Verbesserung')])+f'</dl><p class="muted">{E(f["evidence"])}</p><p>Aktuell: {refs(f["shots"])}<br>Vertiefung vom 9. September: {refs(f["baselineShots"],True)}</p></article>')
 md += [f'### {f["name"]}',' · '.join(f'{c}: {v if v is not None else "—"}/5' for c,v in zip(x['criteria'],f['scores']))]+[f'**{label}:** {f[key]}' for key,label in [('use','Nutzen'),('info','Informationen'),('inputs','Eingaben'),('ui','UI'),('improve','Verbesserung')]]+[f'Nachweis: {f["evidence"]}','Aktuell: '+', '.join(f'[N{n:02d}]({cur[n]})' for n in f['shots'])]
parts+=['</section><section><h2>Empfohlene Reihenfolge</h2>'];md+=['## Empfohlene Reihenfolge']
for r in x['roadmap']:
 parts.append(f'<div class="card"><h3>{E(r["phase"])}</h3><ul>'+''.join(f'<li>{E(t)}</li>' for t in r['items'])+'</ul></div>');md += [f'### {r["phase"]}']+['- '+t for t in r['items']]
parts+=['</section><section id="gallery" class="gallery"><h2>Neue Screenshotgalerie · 10. September</h2><p>Originalaufnahmen, unverändert. Lange Seiten werden als sichtbarer Ausschnitt dokumentiert; ergänzende Ganzseitenbilder stehen im datierten Vorreview.</p><div class="grid">']
for i,s in enumerate(shots,1):parts.append(f'<figure><a href="{cur[i]}" target="_blank"><img loading="lazy" src="{cur[i]}" alt="N{i:02d}: {E(s["name"])}"></a><figcaption>N{i:02d} · {E(s["name"])}</figcaption></figure>')
parts+=['</div><details><summary>74 ergänzende Aufnahmen vom 9. September</summary><div class="grid">']
for i,s in enumerate(oldshots,1):parts.append(f'<figure><a href="baseline-2026-09-09/{i:02d}.png" target="_blank"><img loading="lazy" src="baseline-2026-09-09/{i:02d}.png" alt="B{i:02d}: {E(s["name"])}"></a><figcaption>B{i:02d} · {E(s["name"])}</figcaption></figure>')
parts+=['</div></details></section></main><script>document.getElementById("filter").addEventListener("input",e=>{let n=0;document.querySelectorAll(".feature").forEach(a=>{const show=a.textContent.toLowerCase().includes(e.target.value.toLowerCase());a.classList.toggle("hidden",!show);const row=document.querySelector("tr[data-feature="+a.id+"]");if(row)row.classList.toggle("hidden",!show);if(show)n++});document.getElementById("count").textContent=n+" von 35 Bereichen"});</script></html>']
(P/'index.html').write_text(''.join(parts));(P/'bericht.md').write_text('\n\n'.join(md)+'\n')
# Contact sheets for the complete current set.
for start in range(0,len(shots),12):
 canvas=Image.new('RGB',(1500,1160),'#f4f5f7');d=ImageDraw.Draw(canvas)
 for j,s in enumerate(shots[start:start+12]):
  im=Image.open(P/'screenshots'/s['file']).convert('RGB');im.thumbnail((490,255));xx=(j%3)*500;yy=(j//3)*290;canvas.paste(im,(xx,yy+24));d.text((xx+5,yy+4),s['file'][:-4],fill='#111827')
 canvas.save(P/f'contact-{start//12+1}.jpg',quality=90)
with zipfile.ZipFile(P/'shipyard-ui-review.zip','w',zipfile.ZIP_DEFLATED) as z:
 for file in P.rglob('*'):
  if file.is_file() and file.suffix not in ('.zip','.py'):z.write(file,file.relative_to(P))
print(json.dumps({'new_screenshots':len(shots),'baseline_screenshots':len(oldshots),'features':len(x['features']),'findings':len(x['findings']),'zip_MB':round((P/'shipyard-ui-review.zip').stat().st_size/1e6,1),'report':str(P/'index.html')}))
