'use strict';
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const {test, after} = require('node:test');
const assert = require('node:assert/strict');
const {promisify} = require('node:util');
const execFile = promisify(require('node:child_process').execFile);
let root, db;
after(async () => { if (db?.db.open) db.db.close(); if (root) await fs.rm(root, {recursive: true, force: true}); });
test('activated application archive serves real authenticated routes and rolls back after a fresh process uses it', async () => {
  root = await fs.mkdtemp(path.join(os.tmpdir(), 'application-runtime-recovery-'));
  const source = path.join(root, 'source'); await fs.mkdir(source);
  const playbooks = path.join(root, 'source-playbooks'); await fs.mkdir(playbooks);
  await fs.writeFile(path.join(playbooks, 'recovered.yml'), '- hosts: all\n  tasks: []\n');
  process.env.DB_PATH = path.join(source, 'fleet.db');
  process.env.NODE_ENV = 'test';
  process.env.JWT_SECRET = 'synthetic-runtime-recovery-jwt';
  process.env.FLEET_KEY_SECRET = 'synthetic-runtime-recovery-key';
  db = require('../db');
  const user = db.users.create('recovery-admin', null, require('bcryptjs').hashSync('Recovery-account-password', 4), 'admin');
  require('../utils/crypto').setSecret(db, 'smtp_password', 'synthetic-recovered-smtp');
  db.db.prepare('INSERT INTO environments (id,name) VALUES (?,?)').run('recovery-env', 'Recovered environment');
  db.servers.create({name: 'Recovered host', hostname: 'recovered', ip_address: '192.0.2.45', environment_id: 'recovery-env'});
  const token = require('jsonwebtoken').sign({userId: user.id, tv: user.token_version || 0, sid: require('../utils/auth-sessions').createSession(user)}, process.env.JWT_SECRET, {expiresIn: '1h'});
  const archive = path.join(root, 'application.backup'), prepared = path.join(root, 'prepared');
  const passphrase = 'Synthetic runtime archive passphrase';
  const backup = require('../services/application-backup');
  await backup.createApplicationBackup({database: db.db, destination: archive, passphrase, offline: true, roots: [{id: 'data', path: source}, {id: 'playbooks', path: playbooks}]});
  await backup.restoreApplicationBackup(archive, prepared, passphrase);
  const dataTarget = path.join(root, 'target-data'), playbooksTarget = path.join(root, 'target-playbooks');
  await fs.mkdir(dataTarget); await fs.writeFile(path.join(dataTarget, 'original'), 'preserved original');
  await fs.mkdir(playbooksTarget); await fs.writeFile(path.join(playbooksTarget, 'original.yml'), 'preserved playbook');
  const options = {archive, prepared, passphrase, applicationKey: process.env.FLEET_KEY_SECRET, offline: true, journalDirectory: path.join(root, 'journal'), targets: {database: path.join(dataTarget, 'fleet.db'), roots: {data: dataTarget, playbooks: playbooksTarget}}};
  await require('../services/recovery-activation-stage').stageApplicationActivation(options);
  const switching = require('../services/recovery-activation-switch');
  await switching.activateApplicationRecovery(options);
  const result = await execFile(process.execPath, [path.join(__dirname, 'fixtures/application-recovery-probe.js')], {timeout: 30000, env: {...process.env, DB_PATH: options.targets.database, FLEET_PLAYBOOKS_DIR: playbooksTarget, FLEET_SSH_DIR: path.join(dataTarget, 'ssh'), FLEET_GIT_WORKSPACE_DIR: path.join(dataTarget, 'git'), TOFU_STATE_BACKUP_DIR: path.join(dataTarget, 'state-backups'), PLUGINS_DIR: path.join(dataTarget, 'plugins'), RECOVERY_TEST_OLD_TOKEN: token}});
  const line = result.stdout.split('\n').find(line => line.startsWith('APPLICATION_RECOVERY_RESULT='));
  assert.ok(line, result.stdout);
  assert.deepEqual(JSON.parse(line.slice('APPLICATION_RECOVERY_RESULT='.length)), {health: 200, oldSession: 401, login: 200, hosts: 200, hostRestored: true, playbook: 200, playbookRestored: true, secretRestored: true});
  await switching.rollbackApplicationRecovery(options);
  assert.equal(await fs.readFile(path.join(dataTarget, 'original'), 'utf8'), 'preserved original');
  assert.equal(await fs.readFile(path.join(playbooksTarget, 'original.yml'), 'utf8'), 'preserved playbook');
});
