'use strict';
const {test,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'host-identity-'));
process.env.DB_PATH=path.join(root,'test.db');
process.env.NODE_ENV='test';
const db=require('../db');
require('../features/opentofu/schema').setupOpenTofuDatabase(db.db);
const express=require('express');
const request=require('supertest');
const app=express();
app.use((req,res,next)=>{req.user={role:req.headers['x-role'] || 'admin'};next();});
const router=express.Router();
require('../features/opentofu/routes/vms').registerVmRoutes({db,router,readSavedProxmoxConnection:()=>({base:new URL('https://platform.example.invalid')})});
app.use(router);
after(()=>{db.db.close();fs.rmSync(root,{recursive:true,force:true});});
test('HTTP host relationship returns the inventory name rather than the host alias',async()=>{
 const host=db.servers.create({name:'Host alias',hostname:'alias',ip_address:'192.0.2.10'});
 db.db.prepare('INSERT INTO tofu_proxmox_connections(id,name,endpoint,api_token) VALUES(?,?,?,?)').run('source','Platform','https://platform.example.invalid','fixture');
 db.db.prepare('INSERT INTO proxmox_inventory_servers(server_id,connection_id,node_name,vm_id) VALUES(?,?,?,?)').run(host.id,'source','node',101);
 const cache='tofu.infrastructure.summary.default';
 db.settings.set(cache,JSON.stringify({clusters:[{connections:[{id:'source'}],vms:[{name:'Inventory VM',node_name:'node',vm_id:101,guest_type:'qemu'}]}]}));
 const response=await request(app).get(`/managed-servers/${host.id}`);
 assert.equal(response.status,200);
 assert.equal(response.body.resources[0].vm.name,'Inventory VM');
 assert.equal(response.body.resources[0].connection_id,'source');
 assert.equal(response.body.resources[0].vm.vm_id,101);
 const reader=db.roles.create('Scoped host reader',{canViewServers:true,servers:{servers:[host.id],groups:[]}});
 const allowed=await request(app).get(`/managed-servers/${host.id}`).set('x-role',reader.id);
 assert.equal(allowed.status,200);
 assert.equal(allowed.body.resources[0].vm.name,'Inventory VM');
 const other=db.servers.create({name:'Other host',hostname:'other',ip_address:'192.0.2.11'});
 assert.equal((await request(app).get(`/managed-servers/${other.id}`).set('x-role',reader.id)).status,404);
 const denied=db.roles.create('No host access',{canViewServers:false});
 assert.equal((await request(app).get(`/managed-servers/${host.id}`).set('x-role',denied.id)).status,403);
 db.settings.set(cache,'{}');
 const missing=await request(app).get(`/managed-servers/${host.id}`);
 assert.equal(missing.status,200);
 assert.equal(missing.body.resources[0].vm.name,null);
});
