'use strict';
const {test,after}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'mfa-policy-'));process.env.DB_PATH=path.join(root,'test.db');process.env.NODE_ENV='test';process.env.JWT_SECRET='synthetic-mfa-policy';
const db=require('../db'),express=require('express'),request=require('supertest'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),otp=require('otplib');
const {verifyWsAuth}=require('../ws/auth');const {createSession}=require('../utils/auth-sessions');const auth=require('../middleware/auth');
const app=express();app.use(express.json());app.use('/auth',require('../routes/auth').router);app.get('/protected',auth,(_,res)=>res.json({ok:true}));
const password='Synthetic-policy-password';
const admin=db.users.create('policy-admin','',bcrypt.hashSync(password,4),'admin');
const viewer=db.users.create('policy-viewer','',bcrypt.hashSync(password,4),'viewer');
const login=name=>request(app).post('/auth/login').send({username:name,password});
const get=(url,token)=>request(app).get(url).set('Authorization',`Bearer ${token}`);
const post=(url,token,body={})=>request(app).post(url).set('Authorization',`Bearer ${token}`).send(body);
const socketAllowed=token=>verifyWsAuth({close(){}},new URL(`http://localhost/?token=${token}`));
after(()=>{delete process.env.FLEET_MFA_POLICY;db.db.close();fs.rmSync(root,{recursive:true,force:true});});
test('admin policy restricts enrollment, rejects WebSockets and grants full access only after a real TOTP',async()=>{
 process.env.FLEET_MFA_POLICY='admins';
 const response=await login('policy-admin');assert.equal(response.status,200);assert.equal(response.body.requiresMfaEnrollment,true);
 const token=response.body.token;const payload=jwt.verify(token,process.env.JWT_SECRET);assert.equal(payload.mfa_enrollment,true);assert.equal(payload.exp-payload.iat,600);
 assert.equal((await get('/protected',token)).body.field,'mfa_enrollment_required');assert.equal(socketAllowed(token),false);
 assert.equal((await get('/auth/profile',token)).status,403);assert.equal((await get('/auth/sessions',token)).status,403);
 assert.equal((await get('/auth/totp/status',token)).body.required,true);
 const setup=await post('/auth/totp/setup',token);assert.equal(setup.status,200);
 assert.equal((await post('/auth/totp/confirm',token,{code:'wrong'})).status,400);
 assert.equal((await get('/protected',token)).status,403);
 const confirmed=await post('/auth/totp/confirm',token,{code:otp.generateSync({secret:setup.body.secret})});assert.equal(confirmed.status,200);
 assert.equal((await get('/protected',token)).status,401);
 const full=confirmed.body.token;assert.equal(jwt.verify(full,process.env.JWT_SECRET).mfa,true);assert.equal((await get('/protected',full)).status,200);assert.equal(socketAllowed(full),true);
 assert.equal((await request(app).delete('/auth/totp').set('Authorization',`Bearer ${full}`).send({password})).status,403);assert.equal(db.users.getById(admin.id).totp_enabled,1);
 const ordinary=await login('policy-viewer');assert.equal(ordinary.body.requiresMfaEnrollment,undefined);assert.equal((await get('/protected',ordinary.body.token)).status,200);
});
test('policy changes restrict old password sessions and malformed configuration does not disable enforcement',async()=>{
 process.env.FLEET_MFA_POLICY='optional';const old=(await login('policy-viewer')).body.token;
 process.env.FLEET_MFA_POLICY='all';assert.equal((await get('/protected',old)).status,403);assert.equal(socketAllowed(old),false);
 assert.equal((await post('/auth/totp/setup',old)).status,200);
 const enrollment=(await login('policy-viewer')).body.token;
 process.env.FLEET_MFA_POLICY='optional';assert.equal((await get('/protected',enrollment)).status,403);assert.equal(socketAllowed(enrollment),false);
 process.env.FLEET_MFA_POLICY='typo';assert.equal((await login('policy-viewer')).body.requiresMfaEnrollment,true);
 assert.equal((await post('/auth/logout',enrollment)).status,200);
});
test('mandatory MFA rejects legacy sessions without proof of second-factor verification',async()=>{
 process.env.FLEET_MFA_POLICY='admins';const current=db.users.getById(admin.id);
 const legacy=jwt.sign({userId:admin.id,tv:current.token_version,sid:createSession(current,{})},process.env.JWT_SECRET);
 assert.equal((await get('/protected',legacy)).status,401);assert.equal(socketAllowed(legacy),false);
 const passwordStep=await login('policy-admin');assert.equal(passwordStep.body.requires2FA,true);
 const secret=db.users.getTotpSecret(admin.id);
 const verified=await post('/auth/totp/login','',{tempToken:passwordStep.body.tempToken,code:otp.generateSync({secret})});
 assert.equal(verified.status,200);assert.equal((await get('/protected',verified.body.token)).status,200);
});
test('policy overview is administrator-only and separates disabled, optional and unenrolled accounts',async()=>{
 app.use('/users',auth,require('../routes/users'));
 const disabled=db.users.create('policy-disabled','',bcrypt.hashSync(password,4),'admin');
 db.db.prepare('UPDATE users SET disabled=1 WHERE id=?').run(disabled.id);
 const current=db.users.getById(admin.id);
 const token=jwt.sign({userId:admin.id,tv:current.token_version,sid:createSession(current,{}),mfa:true},process.env.JWT_SECRET);
 process.env.FLEET_MFA_POLICY='admins';
 let response=await get('/users/mfa-policy',token);assert.equal(response.status,200);assert.equal(response.headers['cache-control'],'no-store');
 assert.equal(response.body.requiredAccounts,1);assert.equal(response.body.enrolledRequiredAccounts,1);assert.equal(response.body.optionalAccounts,1);assert.equal(response.body.disabledAccounts,1);assert.deepEqual(response.body.needsEnrollment,[]);
 process.env.FLEET_MFA_POLICY='all';response=await get('/users/mfa-policy',token);
 assert.equal(response.body.requiredAccounts,2);assert.deepEqual(response.body.needsEnrollment.map(user=>user.username),['policy-viewer']);
 assert.deepEqual(Object.keys(response.body.needsEnrollment[0]).sort(),['displayName','id','role','username']);
 process.env.FLEET_MFA_POLICY='unknown';response=await get('/users/mfa-policy',token);assert.equal(response.body.configurationValid,false);assert.equal(response.body.mode,'all');
 process.env.FLEET_MFA_POLICY='optional';
 const viewerToken=(await login('policy-viewer')).body.token;
 assert.equal((await get('/users/mfa-policy',viewerToken)).status,403);
});
