const { test, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'fleet-playbook-revisions-'));
process.env.DB_PATH = path.join(root,'test.db');
process.env.FLEET_PLAYBOOKS_DIR = path.join(root,'playbooks');
process.env.NODE_ENV = 'test';
fs.mkdirSync(process.env.FLEET_PLAYBOOKS_DIR);
const db = require('../db');
const express = require('express');
const request = require('supertest');
const app = express();
app.use(express.json());
app.use((req,res,next)=>{req.user={role:'admin',username:'reviewer'};next();});
app.use('/playbooks',require('../routes/playbooks'));
after(()=>{db.db.close();fs.rmSync(root,{recursive:true,force:true});});
test('playbook writes require observed revision and reject stale or colliding drafts without changing files',async()=>{
 const content='---\n- hosts: all\n  tasks: []\n';
 const create=await request(app).post('/playbooks').send({filename:'review.yml',content,revision:null});
 assert.equal(create.status,200);
 assert.match(create.body.revision,/^[a-f0-9]{64}$/);
 const read=await request(app).get('/playbooks/review.yml');
 assert.equal(read.body.revision,create.body.revision);
 assert.ok(Date.parse(read.body.modifiedAt));
 assert.equal(read.body.status,'draft');
 assert.equal(read.body.author,'reviewer');
 const approved=await request(app).post('/playbooks/review.yml/approve').send({revision:read.body.revision});
 assert.equal(approved.status,200);
 assert.equal(approved.body.status,'approved');
 assert.equal(approved.body.approvedBy,'reviewer');
 const approvedRead=await request(app).get('/playbooks/review.yml');
 assert.equal(approvedRead.body.status,'approved');
 assert.equal(approvedRead.body.approvedBy,'reviewer');
 assert.ok(Date.parse(approvedRead.body.approvedAt));
 assert.equal((await request(app).post('/playbooks').send({filename:'review.yml',content})).status,428);
 assert.equal((await request(app).post('/playbooks').send({filename:'review.yml',content,revision:null})).status,409);
 const newer=content+'# another operator\n';
 const saved=await request(app).post('/playbooks').send({filename:'review.yml',content:newer,revision:read.body.revision});
 assert.equal(saved.status,200);
 assert.notEqual(saved.body.revision,read.body.revision);
 const draftRead=await request(app).get('/playbooks/review.yml');
 assert.equal(draftRead.body.status,'draft');
 assert.equal(draftRead.body.approvedBy,null);
 const staleApproval=await request(app).post('/playbooks/review.yml/approve').send({revision:read.body.revision});
 assert.equal(staleApproval.status,409);
 const conflict=await request(app).post('/playbooks').send({filename:'review.yml',content:content+'# stale\n',revision:read.body.revision});
 assert.equal(conflict.status,409);
 assert.equal(fs.readFileSync(path.join(process.env.FLEET_PLAYBOOKS_DIR,'review.yml'),'utf8'),newer);
 assert.equal(fs.readFileSync(path.join(process.env.FLEET_PLAYBOOKS_DIR,'review.yml.bak.1'),'utf8'),content);
});
