import { useLocation } from '@tanstack/react-router';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import packageInfo from '../../package.json';

const guides = [
  { match: /^\/settings\/notifications(?:\/|$)/, title: 'Notification channels', text: 'Save webhook and email settings separately. Leaving a stored secret unchanged preserves it; use the removal action to clear it. Channel tests send a real message using saved settings. An accepted result confirms endpoint acceptance, not receipt by a person. Inspect Delivery history for failures, partial recipient rejection, duplicates and maintenance suppression.' },
  { match: /^\/settings\/system(?:\/|$)/, title: 'System runtime and collection', text: 'Runtime status distinguishes configured intervals from active timers and running checks. Cycle history covers the current process and resets on restart; a completed cycle can have no eligible targets. Shorter polling intervals increase traffic. Changing the scheduler timezone changes cron-time interpretation across environments, so review upcoming runs afterward.' },
  { match: /^\/settings(?:\/appearance)?\/?$/, title: 'Global branding and personal appearance', text: 'The installation name and brand color apply globally after saving. Clear the name to restore Shipyard. The brand color affects the browser icon and chrome; console controls use your selected theme. Theme and density are personal browser preferences available from the account menu and profile. The VM-ID navigation preference applies immediately in this browser.' },
  { match: /^\/settings\/git(?:\/|$)/, title: 'Git synchronization', text: 'Check remote to refresh repository references without importing files. Review local changes and divergence before pulling or switching branches. Pull requires a clean fast-forward. Push can commit pending local files and publish them; remote read-only blocks it. Connection tests verify repository read access, not push permission. Commit timestamps identify authorship; the last successful pull records an import.' },
  { match: /operations/, title: 'Operations and maintenance', text: 'Select an execution to read its result and log. Acknowledging a failure records that it was reviewed; it does not undo the failure. Schedule maintenance with an owner, host scope and change reference. Overlap warnings identify concurrent work; they do not prevent intentional overlap. Cancel planned or active maintenance with a reason to retain its history and end notification suppression. Editing a repeated window changes only that occurrence.' },
  { match: /deployments/, title: 'VM definitions', text: 'A VM definition describes desired configuration. Save the definition, generate a plan, inspect proposed changes, then apply the reviewed plan. Host adoption is separate: it enables SSH operations without creating a VM definition. An empty definition list does not mean the Proxmox inventory is empty.' },
  { match: /infrastructure/, title: 'Infrastructure inventory', text: 'The tree shows platforms, nodes and their guest VMs or containers. Select an item to inspect its inventory. A separate host icon opens linked host operations. Start and shut down respect the guest lifecycle; force stop interrupts the guest immediately. Use Snapshots to create or restore a recovery point. Restore replaces the guest state with the selected snapshot; verify the guest name and snapshot before confirming. An accepted request is not a completed operation: inspect Tasks for its final result.' },
  { match: /networks/, title: 'IP address management', text: 'Choose a prefix to inspect free and assigned addresses. Reserved holds an address for future use; Active records an address already in use. Verify source and host identity before resolving a synchronization conflict. A healthy connection with zero imported addresses still needs its inventory scope checked.' },
  { match: /servers/, title: 'Host operations', text: 'Use Overview for reachability and attention, Workloads for containers, Updates for OS and custom updates, and Activity for execution history. Image updates are a separate catalog from OS packages. No sample means collection did not provide a metric; it is not a zero measurement.' },
  { match: /playbooks/, title: 'Playbooks and automation', text: 'Review the playbook and selected targets before running. Check mode can help inspect a playbook, but support depends on its modules. Store credentials as secret variables. Review schedules in their configured timezone and inspect execution results after each run.' },
  { match: /settings|profile/, title: 'Access and administration', text: 'Choose user roles deliberately and inspect effective resource access and sensitive capabilities. Configure MFA from the account profile. Treat SSH keys and integration credentials as administrative access. Check integration health after changing connection settings.' },
];
export function ContextHelp({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { pathname } = useLocation();
  const relevant = guides.find(guide => guide.match.test(pathname));
  return <Dialog open={open} onOpenChange={next => !next && onClose()}><DialogContent className="max-w-2xl max-h-[calc(100dvh-2rem)] overflow-y-auto"><DialogHeader><DialogTitle>Shipyard operator guide</DialogTitle><DialogDescription>Guidance for the current page and common operational tasks.</DialogDescription></DialogHeader>
    {relevant && <section className="rounded-md border bg-muted/30 p-4"><h3 className="font-semibold">{relevant.title}</h3><p className="mt-2 text-sm">{relevant.text}</p></section>}
    {guides.filter(guide => guide !== relevant).map(guide => <details key={guide.title} className="rounded-md border p-3"><summary className="cursor-pointer text-sm font-medium">{guide.title}</summary><p className="mt-2 text-sm text-muted-foreground">{guide.text}</p></details>)}
    <p className="text-xs text-muted-foreground">Frontend build {packageInfo.version}. When reporting a problem, include this version, the page, execution ID and reproduction steps. Review logs before sharing them externally.</p>
  </DialogContent></Dialog>;
}
